options:
  rabbit-user:
    default: murano
    type: string
    description: Username used to access rabbitmq queue.
  rabbit-vhost:
    default: openstack 
    type: string
    description: RabbitMQ virtual host to request access on rabbitmq-server.
  database-user:
    default: murano
    type: string
    description: Database username.
  database:
    default: murano
    type: string
    description: Murano database name.
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  verbose:
    default: False
    type: boolean
    description: Enable verbose logging
  region:
    default: RegionOne
    type: string
    description: OpenStack Region
  ext-network:
    default: ext_net
    type: string
    description: |
      The external network to be connect to download the application packages
      on launch of VMs spawned by Murano.
  router:
    default: default_router
    type: string
    description: |
      The default router to bridge the external network and isolated network
      created by Murano for each environment.
  default_dns:
    default: 8.8.8.8
    type: string
    description: |
      The default DNS used by the VMs spawned by Murano to download the
      application packages on poweron.
